<?php

declare(strict_types=1);

namespace App\Rules\Bpm\Actions;

use App\Contracts\BpmAction;
use App\Contracts\BpmActionInterface;
use App\Mail\AgentWelcomeEmail;
use App\Models\Agent;
use App\Models\TaskExecution;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use RuntimeException;

/**
 * SendWelcomeEmailAction
 *
 * Sends the AgentWelcomeEmail to the agent's personal email address.
 *
 * Prerequisites:
 *   - The agent MUST already have `email_corporate` populated
 *     (set by ProvisionITAccountsAction).
 *   - The `_temporary_password` transient attribute MUST be set on the
 *     Agent model (also done by ProvisionITAccountsAction).
 *
 * If the corporate email is missing the action throws a RuntimeException
 * to block the checklist completion — sending an email without credentials
 * would be pointless.
 *
 * Registered in checklist_items.action_class as:
 *   App\Rules\Bpm\Actions\SendWelcomeEmailAction
 */
final class SendWelcomeEmailAction implements BpmAction, BpmActionInterface
{
    use ResolvesTargetAgent;

    public function execute(TaskExecution $execution, array $params = []): void
    {
        $agent = $this->resolveAgent($execution);

        // Corporate email is mandatory — it's generated by ProvisionITAccountsAction
        if (blank($agent->email_corporate)) {
            throw new RuntimeException(
                "Impossibile inviare l'email di benvenuto all'agente #{$agent->id}: "
                . "manca l'email aziendale. Eseguire prima ProvisionITAccountsAction."
            );
        }

        // Decrypt the personal email for sending
        $personalEmail = $agent->email_personal;

        if (blank($personalEmail)) {
            throw new RuntimeException(
                "Impossibile inviare l'email di benvenuto all'agente #{$agent->id}: "
                . "manca l'email personale."
            );
        }

        $temporaryPassword = $agent->getAttribute('_temporary_password');

        // Send the welcome email (queued via ShouldQueue)
        Mail::to($personalEmail)->send(
            new AgentWelcomeEmail($agent, $temporaryPassword)
        );

        Log::info('SendWelcomeEmailAction: welcome email dispatched', [
            'agent_id' => $agent->id,
            'agent_name' => $agent->full_name,
            'recipient' => $personalEmail,
            'queued' => true,
        ]);
    }
}
