<?php

declare(strict_types=1);

namespace App\Mail;

use App\Models\Agent;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Address;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * AgentWelcomeEmail
 *
 * Sent to a newly-provisioned agent's personal email address.
 * Contains their new corporate email and temporary password.
 *
 * The Mailable implements ShouldQueue so delivery is deferred to the
 * queue worker — the BPM checklist checkbox won't block on SMTP latency.
 */
class AgentWelcomeEmail extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    /**
     * The plain-text temporary password generated by ProvisionITAccountsAction.
     * Stored as a transient attribute on the Agent model (not persisted).
     */
    public readonly string $temporaryPassword;

    public function __construct(
        public readonly Agent $agent,
        ?string $temporaryPassword = null,
    ) {
        // Fall back to the transient attribute set by ProvisionITAccountsAction
        $this->temporaryPassword = $temporaryPassword
            ?? $agent->getAttribute('_temporary_password')
            ?? '********';
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            from: new Address(
                config('mail.from.address', 'noreply@' . config('app.domain', 'tuazienda.it')),
                config('mail.from.name', config('app.name', 'UnicoFinance')),
            ),
            subject: 'Benvenuto in ' . config('app.name', 'UnicoFinance') . ' — Le tue credenziali di accesso',
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.agent-welcome',
        );
    }
}
